---
include:
  - project: shore/ci-templates
    file: templates/pre-commit.yml
  - project: shore/ci-templates
    file: templates/docker.yml

stages:
  - test
  - build
  - deploy

build:
  extends: .compose-build
  tags: [host01.shore.co.il]

run:
  extends: .compose-run
  tags: [host01.shore.co.il]
