---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: gtube
      - id: trailing-whitespace
        exclude: \.diff$

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - "-L"
          - "anull"

  - repo: https://github.com/Yelp/detect-secrets.git
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/amperser/proselint.git
    rev: 0.14.0
    hooks:
      - id: proselint
        types: [plain-text]
        exclude: LICENSE

  - repo: https://gitlab.com/devopshq/gitlab-ci-linter.git
    rev: v1.0.6
    hooks:
      - id: gitlab-ci-linter
        args:
          - "--server"
          - https://git.shore.co.il

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/executablebooks/mdformat.git
    rev: 0.7.18
    hooks:
      - id: mdformat

  - repo: https://git.shore.co.il/nimrod/pre-commit-hooks.git
    rev: v0.5.1
    hooks:
      - id: shell-validate
      - id: docker-compose

  - repo: https://github.com/shellcheck-py/shellcheck-py.git
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/AleksaC/hadolint-py.git
    rev: v2.12.1b3
    hooks:
      - id: hadolint
