# vim:ff=unix:ts=2:sw=2:ai:expandtab
---
version: '3.5'
services:
  imap:
    build:
      context: dovecot/
    environment:
      LDAP_BASEDN: &ldap_basedn 'dc=nowhere,dc=com'
      LDAP_URIS: &ldap_uris ldap://slapd
    ports:
      - 993:993
    volumes:
      - _run_dovecot:/run/dovecot
      - mail:/var/mail

  clamd:
    build:
      cache_from:
        - adarnimrod/clamd
      context: clamd/
    image: adarnimrod/clamd
    volumes:
      - _run_clamav:/run/clamav

  spamd:
    build:
      cache_from:
        - adarnimrod/spamd
      context: spamd/
    image: adarnimrod/spamd
    volumes:
      - _run_spamd:/run/spamd
      - mail:/var/mail:ro
      - sa_learn:/var/backups/sa-learn

  crond:
    build:
      context: crond/
    volumes:
      - /run/docker.sock:/run/docker.sock

volumes:
  _run_spamd:
  _run_clamav:
  _run_dovecot:
  mail:
    labels:
      snapshot: 'true'
  sa_learn:
    labels:
      snapshot: 'true'

networks:
  default:
    name: shore
